### ISSUE TITLE
Nothing happens after trying to confirm the SMS

### ISSUE THREAD

**Issue by Jolly-Pirate** [steemit/faucet#359]
A few users have reported that after receiving the SMS, when they click "Continue" on the phone confirmation page, nothing happens. 
Chrome, Firefox, Edge

**Comment by high-octane-soul** [comment]
Hello! I have the same issue!
I was waiting for the verification code on my phone and I did not get on the same day, I got it on the next day. But that's not an issue. The issue is I tried to sign up through my e-mail confirmation link the next day and the screen doesn't process after I enter my phone number! I mean even after pressing the continue button nothing happens! I've attached the screenshot of the situation.

![screenshot 9](https://user-images.githubusercontent.com/39860124/40900368-db3bf932-67e8-11e8-9454-806bd580cd32.png)


please help me out!

**Comment by high-octane-soul** [comment]
Hello! I'm facing the same issue!

I was trying to sigh up and during the process I did not get the phone verification code on the same day, I got it on the next day. Well that's not an issue! The issue is, I tried to continue the sign up process through the e-mail confirmation link and the problem is after entering the phone no. the page doesn't continue to the code verification page at all. I tried pressing the "continue" several times and it did not load at all .. kind of like issue #239 !it is stuck . what do it do ! I've attached the screenshot below .

![screenshot 10](https://user-images.githubusercontent.com/39860124/40900806-02214a28-67eb-11e8-9339-9a18579955a0.png)


Someone please help me out !

**Comment by high-octane-soul** [comment]
Hi guys! My problem is solved! I guess the team worked to debug the issue. Thanks a lot! everything is going smooth. :)

**Comment by TimCliff** [comment]
seems like other users are still having the issue

![image](https://user-images.githubusercontent.com/20735105/40989840-adcdd61a-68b4-11e8-947a-d6f19e9adaf5.png)

**Comment by high-octane-soul** [comment]
Hi! yes even I had the same problem and this is the best platform to share such problems .. dev team will surely work on it and solve the problem.. just have to stay calm and wait for the verification code.. you'll get it within 2-3 days and then you can continue the process.. if you get stuck again leave a message here the dev team will take care of it !

**Comment by TimCliff** [comment]
I asked a user on steem.chat who was having this issue to send a screen shot of their dev console error log. Here is what it shows:

![image](https://user-images.githubusercontent.com/20735105/42581275-faf2d5ae-84f1-11e8-8f09-450284f1c311.png)

**Comment by infleum** [comment]
i wanted to say that the page doesn't let me go further from this page. I did put phone number in, but this 'continue' button is not working, I can't click on it
- 
![image](https://user-images.githubusercontent.com/40813708/42606465-c68f554a-85b8-11e8-8050-bf39ce71eb88.png)

**Comment by jsr1611** [comment]
Any updates on the issue so far??

**Comment by plasmahawknz** [comment]
I am also having this exact issue. Pressing continue does not progress and I do not receive a text. Has anyone found a solution yet?
